python -m nuitka --mingw64 --standalone --lto no run.py \
--plugin-enable=torch --plugin-enable=pylint-warnings --plugin-enable=numpy --enable-plugin=anti-bloat \
--noinclude-pytest-mode=nofollow --noinclude-setuptools-mode=nofollow \
--noinclude-matplotlib --noinclude-scipy \
--nofollow-import-to=PyQt5 \
--nofollow-import-to=matplotlib \
--nofollow-import-to=scipy \
--nofollow-import-to=tkinter \
--nofollow-import-to=torchvision \
--nofollow-import-to=torchaudio \
--nofollow-import-to=IPython \
--nofollow-import-to=jedi \